### ISSUE TITLE
Copy button is missing when in the View Mode

### ISSUE THREAD

**Issue by dcspille** [LightAPIs/joplin-copy-code-blocks#1]
Hello, 

I found this plugin which is awesome by the way, but i can only seem to get the copy button to show up when i have the split view open. 

Here it is visible in split view when hovering over the code block
![image](https://user-images.githubusercontent.com/41346885/222774051-b92f0dd6-c244-4b88-941b-cd76e276c6da.png)

But when i switch to the viewer mode, the cursor changes and the copy button disappears. Is there a setting that I'm missing to make the copy button visible in the view mode?
![image](https://user-images.githubusercontent.com/41346885/222775024-349b0ff0-9423-4465-a203-e14e43e3aef8.png)

**Comment by LightAPIs** [comment]
It seems that Joplin does not allow plugin to inject assets into the Rich Text editor(WYSIWYG), so this function cannot be implemented.

**Comment by LightAPIs** [comment]
I tried to manually add some style or script content to the Rich Text editor renderer, but it was ignored, so it still didn't work.

**Comment by Waldorf3** [comment]
I'm not sure I understand the problem. Is it that you can't paste into teh wysiwyg interface or you can't make the copy button work?   If the former, I often want to copy stuff from code blocks to be used elsewhere outside Joplin so I don't think that matters. If the latter, perhaps the Joplin devs can help? Sorry, just a user here, not sure how things works inside.

**Comment by LightAPIs** [comment]
> I'm not sure I understand the problem. Is it that you can't paste into teh wysiwyg interface or you can't make the copy button work? If the former, I often want to copy stuff from code blocks to be used elsewhere outside Joplin so I don't think that matters. If the latter, perhaps the Joplin devs can help? Sorry, just a user here, not sure how things works inside.

Due to the limitations of WYSIWYG itself, it is not possible to inject code for the copy button into the WYSIWYG editor.
