### ISSUE TITLE
"Copy Code Block" Button Not Functioning in Exported HTML

### ISSUE THREAD

**Issue by mtchoy** [LightAPIs/joplin-copy-code-blocks#3]
**Description:**
The "Copy Code Block" button in the exported HTML file is not working as expected. When attempting to copy the code block from the HTML file, clicking the button does not trigger any action or copy the code to the clipboard. This issue hinders the usability and functionality of the exported HTML file, as users rely on the ability to easily copy code snippets.

**Steps to Reproduce:**
1. Export the HTML file from the application.
2. Open the exported HTML file in a web browser.
3. Locate a code block within the HTML file.
4. Click on the "Copy Code Block" button associated with the code block.

**Expected Behavior:**
After clicking the "Copy Code Block" button, the code block should be copied to the clipboard, allowing the user to paste it into their desired location.

**Actual Behavior:**
Upon clicking the "Copy Code Block" button, no action is triggered. The code block is not copied to the clipboard, and there is no feedback or indication of a successful copy operation.

**Environment:**
- Operating System: MacOS
- Browser: Safari and Chrome

**Additional Information:**
- The "Copy Code Block" button functions correctly within the Joplin application itself, but the issue arises specifically in the exported HTML file.

Thank you for your attention to this matter. Please let me know if any further information is needed.

**Labels:**
- bug
- user-interface
- export-functionality

**Comment by LightAPIs** [comment]
Probably because the [copy operation](https://github.com/LightAPIs/joplin-copy-code-blocks/blob/f659b5e48c4576123cb029323a836e9e280744fb/src/index.ts#L10) is implemented using the Joplin API. However, the API does not exist in the exported HTML. I will try other methods to implement the copy behavior.
